### ISSUE TITLE
 Splash 2.0.0 Blocks Nextcloud

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/unsplash#106]
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [x] This is not a feature request
- [x] This is not an image-provider request
- [x] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**
After updating splash to version 2.0.0 on armhf debian 10 Buster raspberry the plugin crashes nextcloud 24.0.5. which does not happen on debian 11 arm64 raspberry system

**To Reproduce:**
 ----

**Expected behavior:**
----

**Screenshots:**
![Senza titolo](https://user-images.githubusercontent.com/35575744/193792281-14b272d3-10cb-408e-9e15-292aa24ae30e.png)

**Server:**
 - Nextcloud version: 23.0.9.1
 - Splash-App version: 2.0.0

**Additional Information:**

**Comment by skjnldsv** [comment]
Please share your nextcloud log error with us. Search for the specified request ID in your screenshot
Do not share the entire file with us :)

**Comment by newhinton** [comment]
Yes, only the log will help me debug this. My own instance updated fine, but that has nothing to say.

**Comment by tigernero79** [comment]
`{"reqId":"CSeCm3ppRIHAwyBsKxNl","level":0,"time":"2022-10-04T14:03:03+00:00","remoteAddr":"xx.xx.xx.xx","user":"Tiger","app":"user_saml","method":"GET","url":"/index.php/apps/files/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBoots${"reqId":"CSeCm3ppRIHAwyBsKxNl","level":0,"time":"2022-10-04T14:03:03+00:00","remoteAddr":"84.33.95.181","user":"Tiger","app":"encryption","method":"GET","url":"/index.php/apps/files/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBoot`

**Comment by newhinton** [comment]
Is this the full log? It seems cut off and that parts are missing.

I need the error with the code displayed in your screenshot.


Also, next time please follow the bug-template.

**Comment by tigernero79** [comment]
**I am attaching you complete log file, I did regenerate error by re-enabling unsplash with error code id: CSeCm3ppRIHAwyBsKxNl**

[nextcloud.log](https://github.com/nextcloud/unsplash/files/9708090/nextcloud.log)

**Comment by newhinton** [comment]
Which php version do you use? and it seems that the nextcloud version of the error-instance is 23 not 24, i will test that now. Though on x86 not arm

**Comment by newhinton** [comment]
It is very likely that you are running php 7.3. I think i started using class definitions, which are available only on 7.4.

**Comment by marius-wieschollek** [comment]
In that case the php minimum requirement should be increased in the [appinfo.xml](https://github.com/nextcloud/unsplash/blob/master/appinfo/info.xml#L25). Also maybe the update should be removed or more people will try to upgrade to a version that does not run for them.

**Comment by newhinton** [comment]
> In that case the php minimum requirement should be increased in the [appinfo.xml](https://github.com/nextcloud/unsplash/blob/master/appinfo/info.xml#L25). Also maybe the update should be removed or more people will try to upgrade to a version that does not run for them.

Yes i already prepared a version for that. I am currently researching if revoking is possible, can i just "redo" the release with the same tag?

Also it is not verified 100% because i dont have access to a system and i have to set one up, but it seems the most likely.

@tigernero79 Can you test something for me? 
On the server which does not work, can you edit the `nextcloud/apps/unsplash/lib/Provider/Unsplash.php`-file in line 31 and 32, removing `string` and `bool` respectively from the lines?
You may need to do the same for the `nextcloud/apps/unsplash/lib/ProviderHandler/Provider.php`-file.

If you can't do that, thats fine, but then it will take more time for me to replicate your system ;)

**Comment by marius-wieschollek** [comment]
You can delete the release trough the api: https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#api-delete-release

**Comment by tigernero79** [comment]
unfortunately debian buster has php 7.3 in itself, I removed the words bool and string from the lines you mentioned but the error remains, I also modified the second file by deleting all the active string and bool entries but nothing @newhinton

**Comment by newhinton** [comment]
Ah okay, i will try to make it compatible and rerelase it. For now, please disable unsplash via occ until i release 2.0.1

**Comment by newhinton** [comment]
@tigernero79 I have updated the app to 2.0.1, you should be able to update the app in the upcoming hours. It is compatible with php7.3. Please report back if it is fixed for you! (You can also always use git, but you need to use the nextcloud24_providerupdate-branch, not the master-branch!)

**Comment by tigernero79** [comment]
updated to unsplash 2.0.1 everything ok solved thanks for everything 😇

**Comment by newhinton** [comment]
Great! And Sorry for the inconvenience,
