### ISSUE TITLE
Splash app - not displaying random background image as usual

### ISSUE THREAD

**Issue by yondermeister** [nextcloud/unsplash#108]
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [ ] This is not a feature request
- [ ] This is not an image-provider request
- [x] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**
The Splash app doesn't display any image on the background, but it does display it only on the header, on pages that are not the dashboard. On the dashboard, there is the default header and background.
The settings page for this app only displays one option to tick: 'set random image as header background'. The second option 'set random image as background' is absent from this page.

**To Reproduce:**
1. Go to 'Dashboard' and 'other pages'
2. Click on 'App/Splash settings'

**Expected behavior:**
A random background should be showing on all pages.
The settings pages for the splash app should show two options: set random image as header background + set random image as background

**Screenshots:**
See attached files.

**Server:**
 - Nextcloud version: 24.06
 - Splash-App version: 2.01
![splash settings page](https://user-images.githubusercontent.com/41471892/194744527-fa116e1e-4551-4550-9dde-0f8d9dc81df9.jpg)
![dashboard page](https://user-images.githubusercontent.com/41471892/194744534-fd25deb4-3338-492c-b5e0-a30098012e3a.jpg)
![Files page](https://user-images.githubusercontent.com/41471892/194744540-aeb69ad4-9aa5-4ca1-808f-c799a03587bd.jpg)

**Comment by newhinton** [comment]
Did you enable the Dashboard in the server settings? I guess you took a picture of your personal settings where you can disable the header (for visibility-reasons) but the admin-server-settings do expose more settings.

**Comment by yondermeister** [comment]
What you see is my admin account on my Nextcloud, and I have stopped seeing more settings since the last update.

**Comment by newhinton** [comment]
Yes, but which category?

In the personal group there is the Splash category, and in the administration is theming. in the theming category is another splash subcategory where you can select the provider, and where that should be shown.

**Comment by yondermeister** [comment]
OK, got it! Thanks a lot!
