### ISSUE TITLE
l10n: Variables cannot be reordered

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/unsplash#118]
Comment from translator:
`Reordering of variables does not work, if I write e.g. %2$s, it says %s is not present in the translation, so I can't save it.`

https://github.com/nextcloud/unsplash/blob/5bbd7b119016e7f1f0685893954303756a57b219/templates/partials/licenseUnsplash.php#L14

https://github.com/nextcloud/unsplash/blob/5bbd7b119016e7f1f0685893954303756a57b219/templates/partials/licenseWallhavenCC.php#L14

Another translator requested reordering as well.

**Comment by newhinton** [comment]
What exactly is the issue? Do i need to specify the order of the variables and split the array into two parameters? Will that fix the translation-issue?
