### ISSUE TITLE
Compatibility with Nextcloud 27

### ISSUE THREAD

**Issue by MilesTEG1** [nextcloud/unsplash#121]
Hello,

Nextcloud updater show Splash app as incompatible with NC 27.

Will it be an update soon?

Thanks in advance

**Comment by lilianmallardeau** [comment]
If you force the install (by clicking `Enable untested app` in the app store in Nextcloud, or by adding `-f` to the `occ app:install unsplash` command), it seems to work well on Nextcloud 27 tho.

**Comment by MilesTEG1** [comment]
OK, thanks,
I'll try this when I'll upgrade to NC27.

**Comment by newhinton** [comment]
I updated the app to 27!
