### ISSUE TITLE
"We couldn't find this image" - background image is replaced by 404 image

### ISSUE THREAD

**Issue by qudiqudi** [nextcloud/unsplash#134]
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [x] This is not a feature request
- [x] This is not an image-provider request
- [x] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**
Images are not loaded, a 404 error page is shown instead in the background.
background image get's replaced by this 404 error page:

https://images.unsplash.com/source-404?fit=crop&fm=jpg&h=800&q=60&w=1200

**Screenshots:**
![grafik](https://github.com/nextcloud/unsplash/assets/5947641/151c16e4-16cd-4f16-a965-7962890d5377)

**Server:**
 - Nextcloud version: Nextcloud Hub 6 (27.1.5)
 - Splash-App version: latest available via app-store 2.2.1

**Additional Information:**
I can reach unsplash.com just fine from my network, so I doubt it is a dns or geo-block issue (location: Germany)

**Comment by qudiqudi** [comment]
Could be some sort of api/token limit...?

**Comment by timonsky** [comment]
might be some problem with your search terms, eg. returning empty result set. see #125 and #128

**Comment by qudiqudi** [comment]
I've only ever used the defaults, so I doubt that's the problem here. Looking at the issue tracker growing, this git might gonna be stale soon. I've removed this app from my instance, as I don't want to have unmaintained apps running on my personal server. Leaving this open though.

**Comment by newhinton** [comment]
It is also possible that the public unsplash api finally stopped working. The new authenticated api is working already, but you'll need a token for it. I need to update the how-to for that. Also release the current master.

**Comment by cscgeiche** [comment]
The url for the api seems to have changed. There seems to be a new api for getting a random image but you need a api-token to access it. Maybe add a configuration-option for this and let users register at unsplash.

**Comment by newhinton** [comment]
Can you check if this is present in 3.0.0 with the new authenticated api?

It is very likely that the original api was finally closed.

**Comment by cscgeiche** [comment]
With the new API, it seems to work again. I would recommend removing the unauthenticated API from the dropdown.

**Comment by newhinton** [comment]
Closed with v3.0.2. It will remove unsplash and fall back to a supported provider.
