### ISSUE TITLE
source.unsplash.com does not work - maybe use another provider or local pictures

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/unsplash#138]
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [x] This is not a feature request
- [x] This is not an image-provider request
- [x] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**
I installed the app on Nextcloud 29.0.4 and older versions. The app does not work. The problem is the url https://source.unsplash.com/... . I think the server needs an API password. 

**To Reproduce:**
1. use a Nextcloud 
2. install the app Splash
3. check all configurations for Splash
4. on login page i do not get a picture, i get only the default background

**Expected behavior:**
Random picture is loaded.

**Screenshots:**
Normal Nextcloud login screen without the image from Unsplash.

**Server:**
 - Nextcloud version:  Nextcloud 29.0.4
 - Splash-App version: 2.2.1

**Additional Information:**
I think the problem is unsplash.com . I think there is an API needed. Maybe a local directory can be used e.g. something like this.
```

<?php
$dir = __DIR__;
$images = glob($dir . "/*.{jpg,jpeg,png,gif}", GLOB_BRACE);
if (count($images) > 0) {
    $randomImage = $images[array_rand($images)];
    echo "<html><body>";
    echo "<img src='" . basename($randomImage) . "' alt='random image' style='max-width: 100%; height: auto;'>";
    echo "</body></html>";
} else {
    echo "No image found.";
}
?>
```

In my opinion, the Splash app cannot currently work for any user. If I am wrong, please let me know how I can continue to use Splash with Unsplash. I have used the app over many Nextcloud releases and found it really good.

**Comment by newhinton** [comment]
Thank you for using the issue template! However, the original reason for my closure was not because of the template, but because there are some duplicates to this request.

It is known that unsplash closed their original API, which is currently beeing replaced by the new one (#115). Also there is another issue (#70) for the local gallery.
