### ISSUE TITLE
NC 29: Login screen not working

### ISSUE THREAD

**Issue by mwinkens** [nextcloud/unsplash#139]
- Nextcloud version: 29.0.2
 - Splash-App version: 3.0.0

![Bildschirmfoto vom 2024-08-05 11-55-45](https://github.com/user-attachments/assets/75c16b49-09cd-4704-970d-52b433c8d3fb)

(Note: I am aware, that the directory says nextcloud28, but this is really a nextcloud 29 instance, since it just updated)

**Comment by mwinkens** [comment]
@ISeeTWizard that's just factually wrong? look here: https://github.com/nextcloud/unsplash/pull/133
Also it's supported to Nc28, there is just a new release missing.

On another side I also removed it for now, since I needed to upgrade, and opted into using `php occ theming:config background <path>` with a cronjob where I select a random image every 10 minutes from my own image directory

**Comment by ISeeTWizard** [comment]
You might see it like this I see it that the last official support was NC27 (as written in the NC DB which you can view by yourself) and it’s been last official updated over a year ago
And for me that’s an actual dead product until a new release may come out or may not
That we will see in the future - they seem to be working on NC29 support but till an official release it doesn’t exist

yes it worker on NC28 but it never was official supported, at least as written on the official NC DB - App Store
And I refer to those info:

https://apps.nextcloud.com/apps/unsplash

**Comment by nd-** [comment]
This PR https://github.com/nextcloud/unsplash/pull/140 fixes the login screen, but the background image still doesn't load.
It seems the API has changed, and this request https://source.unsplash.com/featured/1920x1080?forest does not work anymore.

**Comment by fuf42** [comment]
> did you change provider to UnsplashAPI and entered your API token after creating a account at Unsplash? It is working fine for me since then

for me the login screen still crashes in this combination (UnsplashAPI and nc 29.0.5

**Comment by newhinton** [comment]
> for me the login screen still crashes in this combination (UnsplashAPI and nc 29.0.5

with the fix provided by #140 ?

**Comment by nd-** [comment]
> did you change provider to UnsplashAPI and entered your API token after creating a account at Unsplash? It is working fine for me since then

Where do you change that setting ? I didn't see...

**Comment by nd-** [comment]
> Where do you change that setting ? I didn't see...

Oh! I didn't see the select in /settings/admin/theming, to choose UnsplashAPI...

**Comment by masterwishx** [comment]
> Hi @nd-
> 
> did you change provider to UnsplashAPI and entered your API token after creating a account at Unsplash? It is working fine for me since then

We should use Unsplash API? Unsplash not working?

**Comment by Jorysm** [comment]
I'm sorry, but take that token?
