### ISSUE TITLE
NC 28 still not working

### ISSUE THREAD

**Issue by CrazyWolf13** [nextcloud/unsplash#142]
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [x] This is not a feature request
- [x] This is not an image-provider request
- [x] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**
For me it still does not show any unsplash background.

**To Reproduce:**
1. Install 3.0.0 of Splash
2. Enable Splash
4. Go to theming and configure splash to use unsplash as source
5. Still see the blue background, but the unsplash i for info I guess
6. See a lot of errors in log:

**Expected behavior:**
I expect a working background.

**Screenshots:**
Logs:
![grafik](https://github.com/user-attachments/assets/7ed72d2e-8162-4a45-99f2-d47320ef6c88)
Info section, bottom right
![grafik](https://github.com/user-attachments/assets/481e3cdc-91cb-4df0-bdca-54861c6a09c0)

**Server:**
 - Nextcloud version: 28.0.9.1
 - Splash-App version: 3.0.0

**Additional Information:**

**Comment by newhinton** [comment]
Please switch to a different provider. Unsplash (the non api-variant is non working, and will be removed in the close future)

**Comment by CrazyWolf13** [comment]
Oh I see, I couldn't find that info anywhere, thanks for clarification!

I've just registered an app on Unsplash, but seems like it needs all manual review, is that correct?

**Comment by newhinton** [comment]
If i remember correctly, no. You should be able to get the token and use it. You might need to click the refresh button above the provider selector.

Though i can check this in the evening if you like

**Comment by CrazyWolf13** [comment]
Okay, thanks it worked now, it was a bit confusing which token to use, as it's called access key and there is also a secret key.

However now it's getting the correct description and preview is working, however the image is still blue:
![grafik](https://github.com/user-attachments/assets/f181ff8d-ea6f-41eb-a986-b1c5ee0c6d51)
There are no log entries.

**Comment by CrazyWolf13** [comment]
@newhinton 

So I just looked at this again today, and surprisingly the image was changed on the dashboard now.
I tried to reboot, log-in/out etc. I stayed blue, today morning it just worked.
But I noticed an blue color all over it so disabled the vibrat color or so, but it does not seem to apply.

Could there be some sort off apply mechanic not working on the dashboard image?

Because chaning the cached image changes the image jut fine on the login screen, but dashboard just stays the same, and will most likely be changed during night or so?

**Comment by newhinton** [comment]
It is likely that this is a caching issue. For "unsplash-api" and "wikimedia pic of the day" we fetch the image once a day, and then just serve that. However, browsers usually cache the css files, so that they dont get the update immediately. I'll have to look into that if i want to change that.

**Comment by CrazyWolf13** [comment]
> It is likely that this is a caching issue. For "unsplash-api" and "wikimedia pic of the day" we fetch the image once a day, and then just serve that. However, browsers usually cache the css files, so that they dont get the update immediately. I'll have to look into that if i want to change that.

That could be very well possible, I thought about caching.

So checking in now, it seems to display correctly, so possibly it just needs that daily refresh-fetch to apply the settings.

**Comment by desentizised** [comment]
Not trying to complain or vent I just came across this app by browsing through the catalog on a fresh NC 29 FPM install (dockerized) and it made my login-screen Error 500 after installing. 

I didn't check whether there were some administrative settings (I think I saw mention of an api-key around here) which I should've attended to before unbeknownst locking myself out of the web interface (was trying to switch user). If this is expected behavior on 28/29 because the final release isn't there yet this comment may be disregarded. Just trying to add to the conversation since OP's description doesn't seem to talk about a complete breakage of the login-page. 

Unsplash was listed as an untested app for me so I don't blame anyone but myself.

**Comment by newhinton** [comment]
v3.0.1 should fix all those issues. The old unsplash has been removed and replaced by wikimedia as a fallback.

**Comment by newhinton** [comment]
@desentizised This is a known issue, 3.0.0 simply does not work on 29. (Though, 3.0.1 _does_ work)

**Comment by CrazyWolf13** [comment]
Thanks!
