### ISSUE TITLE
Unsplash 3.00 leads to Internal Server Error in Nextcloud 29.06

### ISSUE THREAD

**Issue by tobefrank1** [nextcloud/unsplash#144]
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [x ] This is not a feature request
- [ x] This is not an image-provider request
- [ ] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**
<Unsplash 3.00 leads to Internal Server Error in Nextcloud 29.06 after relogin/restart.
Uninstalling Unsplash reversed the problem. 

>

**To Reproduce:**
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior:**

**Screenshots:**

**Server:**
 - Nextcloud version: 
 - Splash-App version: 

**Additional Information:**

**Comment by newhinton** [comment]
Duplicate #139
