### ISSUE TITLE
`ILogger` is deprecated and will be removed

### ISSUE THREAD

**Issue by susnux** [nextcloud/unsplash#148]
The `ILogger` interface is deprecated and its logging functions will be removed with Nextcloud 31.
Please migrate to the PSR LoggerInterface. The logging levels inside `ILogger` will remain, but we recommend to use the logging levels provided by PSR-3.

Code reference:

https://github.com/nextcloud/unsplash/blob/8305b00e0b31ecc07340e1750f4e592a233fba56/lib/ProviderHandler/Provider.php#L57

https://github.com/nextcloud/unsplash/blob/8305b00e0b31ecc07340e1750f4e592a233fba56/lib/Cron/ImageProviderBackgroundFetch.php#L17

https://github.com/nextcloud/unsplash/blob/8305b00e0b31ecc07340e1750f4e592a233fba56/lib/Services/SettingsService.php#L75

https://github.com/nextcloud/unsplash/blob/8305b00e0b31ecc07340e1750f4e592a233fba56/lib/EventListener/BeforeTemplateRenderedEventListener.php#L39

https://github.com/nextcloud/unsplash/blob/8305b00e0b31ecc07340e1750f4e592a233fba56/lib/ProviderHandler/ProviderDefinitions.php#L55

cc @newhinton @come-nc

**Comment by newhinton** [comment]
Closed with 5c00a48d
