### ISSUE TITLE
Reported as not compatible with NC 30.0

### ISSUE THREAD

**Issue by waja** [nextcloud/unsplash#149]
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [x] This is not a feature request
- [x] This is not an image-provider request
- [x] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**

Hi there,

as Nextcloud 30 was released yesterday, it might be blocking users from upgrading cause unsplash is reported as not compatible.

Thanks, Jan.

**Comment by newhinton** [comment]
That is true, however, i don't think there have been any breaking changes, so it should still work. I will implement #148 and then release an update.
