### ISSUE TITLE
The Polling URL does not start with HTTPS despite the login URL started with HTTPS.  Login will not be possible because this might be a security issue. 

### ISSUE THREAD

**Issue by reinvk** [nextcloud/unsplash#150]
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [x ] This is not a feature request
- [x] This is not an image-provider request
- [x ] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**

I have installed a docker nextcloud container in Docker on Ubuntu Linux. I have a NGINX reverse proxy manager running on a Raspberry pi4. When i want tot connect with a Desktop (Windows) client with the https://URL.me the messages appears: 

The Polling URL does not start with HTTPS despite the login URL started with HTTPS. 
Login will not be possible because this might be a security issue. 

When i use the webbrowser with the same URL https://URL.me it work oke. I have spend many, many hours to search a solution so there are/were many people who had this issue and tried tot solve it in the same way they did. 
But nothing was working for me.

**To Reproduce:**
1. Go to Windows or iOS Nextcloud client
2. Click on Login and type the URL https://URL.me
3. Click on the arrow to connect and then a windows pops up with the message: 
   The Polling URL does not start with HTTPS despite the login URL started with HTTPS. 

**Expected behavior:**

**Screenshots:**

![afbeelding](https://github.com/user-attachments/assets/ce51c0a7-9dad-4971-8b8a-d3af6dd50275)
then
![afbeelding](https://github.com/user-attachments/assets/0ad56dea-d2b6-45d6-ac2b-bbb5382b5851)
then
![afbeelding](https://github.com/user-attachments/assets/f4664fd7-cba8-4a3e-bb8c-b347ec69ec6b)

**Server:**
 - Nextcloud version: 29.0.7
 - Splash-App version: 
 - Nexcloud Hydrgen for iOS : 5.5.5.0

**Additional Information:**

NGINX reverse proxy manager verion: v2.10.4

Can you please help me tot troubleshoot and find the right solotion

**Comment by newhinton** [comment]
This does not seem to be related to unsplash. I guess you did not properly configure the reverse proxy.

For help with setting up nextcloud, pleade use the forum:
https://help.nextcloud.com/

**Comment by reinvk** [comment]
Sorry for putting this issue into the wrong place. Thank you for your answer.

**Comment by reinvk** [comment]
sorry this issue is not correct posted, I will close it now.

**Comment by reinvk** [comment]
Close this issue into the wrong posted location
