### ISSUE TITLE
Nextcloud 30 - 3.0.2 in official store

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/unsplash#151]
Can you please push the current version 3.0.2 to the official Nextcloud Store?
There is only the 3.0.1 shown.

Great thanks.

**Comment by FlattusBlastus** [comment]
I updated to NC 30.0.1 develop and only see Splash 29 in the store

**Comment by asheroto** [comment]
Same

**Comment by newhinton** [comment]
Splash should still work with nextcloud 30. You can enable it as an untested app.

**Comment by asheroto** [comment]
I did, but am seeing errors. I created a separate bug report. #152

**Comment by Siggi0904** [comment]
only with splash 3.0.2 it's ready for Nextcloud 30.

That means, dev's have to push new version 3.0.2 from git to the official nextcloud store.
As long 3.0.2 is not at the official store and you upgrade nc to 30.x the app should be deactivated.

Thanks.

**Comment by Siggi0904** [comment]
But there is wrong at release notes for version 3.0.3.

Nextcloud 30 comes with Nextcloud Hub Version 9 not 7.
