### ISSUE TITLE
Undefined array key "Unsplash"

### ISSUE THREAD

**Issue by asheroto** [nextcloud/unsplash#152]
- [X] This is not a feature request
- [X] This is not an image-provider request
- [X] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**
The log file is filled with this error message:
```
Undefined array key "Unsplash" at /var/www/nextcloud/apps/unsplash/lib/ProviderHandler/ProviderDefinitions.php#95
```

**To Reproduce:**
1. Install on Nextcloud 30
2. Click around and use the system
3. Check the Logging section of the admin panel

**Expected behavior:**
No errors

**Screenshots:**
![Image](https://github.com/user-attachments/assets/cc3e5768-179e-4d59-a30d-b2b8fee7ff61)

**Server:**
 - Nextcloud version: 30.0.1
 - Splash-App version: 3.0.1

**Comment by newhinton** [comment]
This is a duplicate: https://github.com/nextcloud/unsplash/issues/147

**Comment by asheroto** [comment]
Oops, sorry. Not sure how I missed that in search.
