### ISSUE TITLE
Use daily or weekly images instead of random

### ISSUE THREAD

**Issue by milosz** [nextcloud/unsplash#19]
Thanks for this Nextcloud app, it is great! I would like to propose enhancement to use weekly or daily images instead of random to get more smooth experience.

**Comment by jancborchardt** [comment]
Could be an interesting enhancement, although the randomness is kinda what makes it nice. :)

**Comment by jancborchardt** [comment]
This is super related to #4 (Add possibility to customize Unsplash URL) because if we implement that, you can use anything they documented at https://source.unsplash.com/ :) For example https://source.unsplash.com/daily

**Comment by livier** [comment]
I found a solution for customize backgroung color and image choice. 
Install "Custom CSS" and then insert anything like
```
body#body-login
{
    background-color    : #700 !important;
    background-image    : url('https://source.unsplash.com/random/featured/?earth-planets') !important;
}
```
Enjoy

**Comment by newhinton** [comment]
Moved. see #94
