### ISSUE TITLE
Allow setting resolution

### ISSUE THREAD

**Issue by BentHaase** [nextcloud/unsplash#24]
The app is really nice and pictures are good but for higher resolution screens a setting to allow increasing the resolution would be neat.

On HiDPI (4k+) screens the images look really blurred and unsharp. Of course this is also dependant on the source quality of the pic but in 2018 the images should be at least 1080p or above.

**Comment by jancborchardt** [comment]
This is super related to #4 (Add possibility to customize Unsplash URL) because if we implement that, you can use anything they documented at https://source.unsplash.com/ :)

An example for a 4k image url you could put in to get a nature image is https://source.unsplash.com/3840x2160/?nature

**Comment by Judocrafter** [comment]
Is it possible to add a Collection in the URL?
like https://unsplash.com/collections/2463648/4k-wallpapers ?

Thank you

**Comment by newhinton** [comment]
see #94
