### ISSUE TITLE
Add possibility to customize unsplash url

### ISSUE THREAD

**Issue by mjanssens** [nextcloud/unsplash#4]
I like this simple but nice feature.
Perhaps a nice addition would be to customize the url.
Or maybe even better to use the api from unsplash for collections or searches

**Comment by sunjam** [comment]
Customizing the url would also allow Unsplash users to switch to their own collections.

**Comment by joewashear007** [comment]
I think this would be really helpful. I love the idea but it is really weird when you random picture of people that are not appropriate for work. Maybe at least switch the default URL to pull nature or still life photos?

**Comment by jancborchardt** [comment]
Contributions here are very welcome. :) It would need to be an admin setting, a simple input box with the current URL and below a link to their API documentation.

As of now, you can already edit the URL manually in the CSS file.

**Comment by livier** [comment]
I found a solution for customize backgroung color and image choice.
Install "Custom CSS" and then insert anything like

body#body-login
{
    background-color    : #700 !important;
    background-image    : url('https://source.unsplash.com/random/featured/?earth-planets') !important;
}

Enjoy

**Comment by v0d** [comment]
> I found a solution for customize backgroung color and image choice.
> Install "Custom CSS" and then insert anything like
> 
> body#body-login
> {
> background-color : #700 !important;
> background-image : url('https://source.unsplash.com/random/featured/?earth-planets') !important;
> }
> 
> Enjoy

This does not easily work anymore due to:

```
Refused to load the image 'https://source.unsplash.com/random/featured/?asia' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".
```

**Comment by livier** [comment]
Still work here.

**Comment by newhinton** [comment]
Moved. see #94
