### ISSUE TITLE
Request: Support other creative commons photo sites

### ISSUE THREAD

**Issue by sunjam** [nextcloud/unsplash#5]
Why?  Because there are great alternatives to Unsplash that are also freely available under a creative commons zero license.  It adds other options + connects users with a lot of great Creative  Commons content.

[Pixabay - Creative Commons Zero with absolutely no credit needed to use the images.](https://pixabay.com/)
[Pexels is another Creative Commons Zero page with tons of great photos](https://www.pexels.com/)
[Wikimedia Commons has a great picture of the day as CC0](https://commons.wikimedia.org/wiki/Main_Page)
[Librestock](http://librestock.com/search/?query=cute&origin=PX&origin=MG&origin=FC&origin=SS&origin=PB&origin=TP&origin=KP&origin=PJ&origin=LS&origin=LV&origin=SP&origin=JM&origin=MT&origin=FN&origin=BA&origin=FP&origin=BI&origin=GS&origin=IP&origin=PG&origin=NS&origin=SH&origin=RS&origin=SW&origin=BF&origin=LP&origin=PD&origin=BL&origin=FB&origin=CV&origin=DP&origin=FS&origin=TC&origin=FF&origin=MS&origin=IR&origin=JS&origin=SK&origin=JH&origin=MI&origin=IJ&origin=AI&origin=PA&origin=SF&origin=LG&origin=NP&origin=AP)
[Negativespace with great CC0 photos](https://negativespace.co/)

**Comment by e-alfred** [comment]
Way better: Support of pictures stored on Nextcloud itself. It would be awesome to simply set a folder with pictures in settings that will show up on the login screen.

**Comment by sunjam** [comment]
@e-alfred That is a different, but equally awesome request.  It makes total sense to host a directory of pictures on your own cloud (no pun intended).  I've created Issue #6 for your request.

**Comment by jancborchardt** [comment]
If someone wants to contribute here I'd appreciate it. Unsplash is actually _not_ CC0 because of their arbitrary clause that you can't use the pictures to build an alternative to Unsplash …

So I would very much like to see a switch of the whole app to Wikimedia Commons. They have a complicated API beyond a simple URL so any help is appreciated.

**Comment by dadosch** [comment]
For **Wikimedia** POTD, there is actually a PHP class https://github.com/simison/WikimediaCommonsPotd

For **Pixabay**, you would have to download the image  beforehand: 
>NO HOTLINKING - what does that mean?
If you want to show Pixabay images on your website, please upload them to your server. Pixabay image URLs don't work on external sites.

**Comment by livier** [comment]
As [asked](https://github.com/nextcloud/unsplash/issues/70#issuecomment-787103865) here are some suggestions. 

I see (and have) many suggestions for source off pictures to show. 
It could be selected in the setup space. I hacked that [here](https://github.com/nextcloud/unsplash/issues/4#issuecomment-533601216) using "Custom CSS". I can change the url source of pictures. I do it changing search words on unsplash. Not tested giving another server link ... 
For a specific gallery, the admin could have access to a dedicaced directory where his put the pictures. This directory should be only accessible on the setup UI of the app, or be shearable with a list of users selected on the setup. The admin is responsible of the pictures, or the users who he gives the access to put pictures there. Specify this responsability in case a user places there a nonsence or porn picture on splash !!
If my english is not clear, ask ...

**Comment by newhinton** [comment]
I have now implemented the basis for this. There is a quick way to add new provider, so if you know any provider feel free to post a link with the public api!

**Comment by newhinton** [comment]
Moved. see #94
