### ISSUE TITLE
Nextcloud 17 compatibility

### ISSUE THREAD

**Issue by j-ed** [nextcloud/unsplash#50]
@jancborchardt Can you please provide an updated version of this app.

**Comment by jancborchardt** [comment]
So @nextcloud/unsplash took over maintainership of the app, namely @newhinton and @marius-wieschollek :)

**Comment by newhinton** [comment]
@j-ed

sure, i will solve this shortly, in the next few days! :D

**Comment by newhinton** [comment]
See #51

**Comment by R7800** [comment]
Removed 1.1.3, installed 1.1.4 but images don't load on NC17 (both php-fpm ang webserver restarted). Images were loaded on NC16 with same PHP and webserver versions.

**Comment by waja** [comment]
I'd recommand to try Incognito Modus of your Browser to test the installation.

**Comment by R7800** [comment]
Found source of this problem - Privacy Badger has blocked images.unsplash.com and source.unsplash.com, allowing cookies from these domains solves problem.
I never changed Privacy Badger's setting as in previous NC versions images were loaded.
