### ISSUE TITLE
Anyone else notice images have stopped?

### ISSUE THREAD

**Issue by Oclair** [nextcloud/unsplash#52]
I updated NC today to 16.0.7 and noticed the unsplash images are no longer displaying.
It seems it's been quiet here for a while, do we need to provide a key per instance or something?

Thanks for a great plugin!
Happy New Years,
OC

**Comment by marius-wieschollek** [comment]
The app is working fine for me. Could it be that the update disabled it or that the background images were disabled in the settings?

**Comment by Oclair** [comment]
Specifically without much investigation, I believe the new suggested nginx server settings have changed the ability for remotely hosted content on a logged in page.

So my settings with nginx we're made compliant to block the vulnerability over here:
https://nextcloud.com/blog/urgent-security-issue-in-nginx-php-fpm/

**Comment by Oclair** [comment]
my previous post is an important topic but unrelated to the issue,  Privacy Badger on Firefox had unspash blocked (how did they get there?)  It appears there may be some leaked info being sent to unsplash.  It may be a good time to mention we might need an ethical alternative to unsplash.

Thank you all for your contributions to this project and the community in general!
