### ISSUE TITLE
Nextcloud 18 compatibility

### ISSUE THREAD

**Issue by j-ed** [nextcloud/unsplash#54]
@newhinton, @marius-wieschollek can you please provide an updated version which supports Nextcloud 18.

**Comment by newhinton** [comment]
Ah sorry yes. Will be a few days though :/

**Comment by newhinton** [comment]
#55

**Comment by oucil** [comment]
+1

**Comment by newhinton** [comment]
https://github.com/nextcloud/unsplash/releases/tag/v1.1.5
