### ISSUE TITLE
How can I change the picture source

### ISSUE THREAD

**Issue by RRRRRm** [nextcloud/unsplash#58]
I am in China. Our government have blocked unsplash.com . 

I have some other random picture API that I can access, like `https://api.ixiaowai.cn/gqapi/gqapi.php` `https://img.xjh.me/random_img.php`

What should I do to change the picture source.

**Comment by newhinton** [comment]
Hope you are doing fine!


To your question:

First, you need to allow that url in this file, just copy the line and enter the domainname there:
https://github.com/nextcloud/unsplash/blob/f77d6421a83e838eb4a3b5e4fdbd607c165058fc/lib/AppInfo/Application.php#L77

then, you need to edit the used url in the css file here:
https://github.com/nextcloud/unsplash/blob/f77d6421a83e838eb4a3b5e4fdbd607c165058fc/css/login.css#L4

and here:

https://github.com/nextcloud/unsplash/blob/f77d6421a83e838eb4a3b5e4fdbd607c165058fc/css/header.css#L5

That should be it!
However, you can only use one provider at a time.

**Comment by RRRRRm** [comment]
It works, thank you!
