### ISSUE TITLE
Request: Backgrounds images from a folder within Nextcloud

### ISSUE THREAD

**Issue by sunjam** [nextcloud/unsplash#6]
Allow images to also be supported from a directory selectable within the local Nextcloud instance.  References issue #5

**Comment by jancborchardt** [comment]
Is anyone down to submit a pull request for this? :)

**Comment by Shadowstreik** [comment]
Hello. What would the status of this be? Thank you.

**Comment by jancborchardt** [comment]
@Shadowstreik see label: **help wanted** :)

**Comment by Shadowstreik** [comment]
That doesn't tell anyone anything and that last post was months, ago. What has transpired in the vast amount of time that has passed. Thank you for taking the time to look into it.

**Comment by sunjam** [comment]
Hi, I’m OP.  We are all on the same team so please remain respectful to the Nextcloud devs.  This is an open request and clearly not a top priority.  If you are not a developer, please help us find someone to assist.  The issue remains open in good faith.

**Comment by jancborchardt** [comment]
> What has transpired in the vast amount of time that has passed.

@Shadowstreik nothing, otherwise there would be an update right here in this issue. :) If you know any developers who would like to contribute, please point them this way.

**Comment by ASmith-** [comment]
Seems like a start on this would be to merely setup a folder within NextCloud the add-on randomly selects the background images to use. That's what,  a 30 minute coding effort by a developer familiar with this project? Then a developer down the road could possibly look to have the option of multiple additional background images pulled from remote sites or locations.

**Comment by splashote** [comment]
Hey! 
I'd totally love this feature!
I will ask around if I find someone who wants to try it.

**Comment by newhinton** [comment]
Moved, see #94
