### ISSUE TITLE
Suggestion: be able to set the Unsplash parameter for API from the web

### ISSUE THREAD

**Issue by zarma30** [nextcloud/unsplash#63]
Hi,

Your Unsplash pluggin is great, but from my point of you should be accesible for non technical users, letting them changing the API parameter from the web interface (f.eg: 
- https://source.unsplash.com/user/erondu/1600x900
- https://source.unsplash.com/user/rischfre/likes/1600x900
- https://source.unsplash.com/collection/190727/1600x900
)
and not letting the nature themes fixed or changing the login.css file each plugin update).

Thanks in advance.

**Comment by vcbranco** [comment]
Great idea,

A way of being able to choose a Unsplash collection

**Comment by newhinton** [comment]
Moved. See #94
