### ISSUE TITLE
Set header picture as "off" globally? (also for "shared files screen"?)

### ISSUE THREAD

**Issue by edo0** [nextcloud/unsplash#64]
System details:
- NC 19.3.0
- Debian 10.
After installing Unsplash, I have realized that the header setting is automatically enabled globally for all users. I have proceeded to disable it on the few accounts on my instance, only to discover that it will _persist for non-registered users_ → any time I share I file or a poll externally, the header will present background Unsplash pictures.
Is there a way to change this?
Thank you in advance!

**Comment by marius-wieschollek** [comment]
You can set this in the "Theming" section of the Nextcloud admin settings

**Comment by edo0** [comment]
Good to know. 
I was keeping Theming disabled, that's apparently why I could not fix it. So for anyone who may have the same issue, please do as follow:
- enable Theming
- from Theming, disable random pictures in headers
- disable Theming
- Enjoy!
