### ISSUE TITLE
[NC 20 RC2] Log message: /appinfo/app.php is deprecated

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/unsplash#65]
In the NC20 RC2 version, the following message appear in the log:
![obraz](https://user-images.githubusercontent.com/47037905/94305072-eadd1980-ff70-11ea-9a35-0df08f8254c1.png)

App:
Splash 1.1.6

### Server configuration

**Database:**
phpMyAdmin

**PHP version:**
7.3.16

**Nextcloud version:** (see Nextcloud admin page)
20.0.0 RC2

**Comment by newhinton** [comment]
This is released in (1.2.0)[https://github.com/nextcloud/unsplash/releases/tag/1.2.0]!
