### ISSUE TITLE
Compatible with NC20 

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/unsplash#66]
Splash is not compatible with Nextcloud 20.

**Comment by newhinton** [comment]
See [comment](https://github.com/nextcloud/unsplash/issues/67#issuecomment-706770823) :D

**Comment by newhinton** [comment]
@Valdnet Do you have issues with Splash besides the warning that it is an untested app? I will fix the wrong version number, but besindes that, i cant find issues with unsplash

**Comment by Valdnet** [comment]
@newhinton No. I have no problems with Splash. The only thing that occurs is #65.

**Comment by newhinton** [comment]
I released 1.1.7 which restores compatibility. It does not fix #65, which will be fixed later.
