### ISSUE TITLE
Dashbord Background Image

### ISSUE THREAD

**Issue by Weasy666** [nextcloud/unsplash#67]
I don't know if it is possible, but it would be nice, if unsplash could also change the background image of the newly added dashboard.

**Comment by newhinton** [comment]
This seems like a good idea! I will see if i can get around that in the upcoming week

**Comment by Weasy666** [comment]
Very nice! Thank you for that!

**Comment by newhinton** [comment]
It seems that this is not possible at the moment. (At least not in any reasonable way). It can be implemented when the dashboard exposes the background image.

https://github.com/nextcloud/server/issues/23476

**Comment by dartcafe** [comment]
Anyway an API for retrieving the last or a new picture would be great, so other apps could consume this (and the dashboard as well).

**Comment by newhinton** [comment]
I just released [1.2.0](https://github.com/nextcloud/unsplash/releases/tag/1.2.0) with the dashboard-update!

**Comment by junpet** [comment]
I see `We couldn't find that photo` background, when I set `Set random image as dashboard background`. I can't see any error in the Settings > Logging. The Log in page is working fine with random background image.

I use Nextcloud 20.0.5 (Docker Alpine version).

Let me know if you need more info.
