### ISSUE TITLE
Javascript error at settings page

### ISSUE THREAD

**Issue by hype11** [nextcloud/unsplash#69]
If I goto the settings page (with admin rights) I get the following javascript error:
![nextcloud_firefox_error](https://user-images.githubusercontent.com/33953581/100624492-d0823c00-3323-11eb-814b-a977c4d5651a.png)

Version: - Splash 1.1.7
             - nextcloud 20.0.2

**Comment by marius-wieschollek** [comment]
Is this on the personal settings page or the Nextcloud theming page?

**Comment by hype11** [comment]
personal settings
nextcloud_server/settings/user

**Comment by newhinton** [comment]
Since jquery was replaced, this should be fixed
