### ISSUE TITLE
Request: Pull image(s) in advance with cronjob to have it ready uppon loading the page

### ISSUE THREAD

**Issue by konstantinwall** [nextcloud/unsplash#7]
I experience a little delay when I load my cloud page until the image is shown. It would be great to pull the next image with the cronjob. Information if this image was then shown to the user could be kept in database. So that if a image was pre cached, it is no necessary to cache another one, until the previous was shown once.

Besides that ... I love your App (idea). It is simple and beautiful!

**Comment by jancborchardt** [comment]
Yeah, performance could be improved. However this specific solution would incredibly increase the complexity from a simple URL call which shows the current inage to having a database. Sorry but I'm not very fond of that. :)

**Comment by jancborchardt** [comment]
If we support other creative commons photo sites #5 then this could be an option.
