### ISSUE TITLE
Compatibility with NC21

### ISSUE THREAD

**Issue by goldgoldfish** [nextcloud/unsplash#84]
Is it planned that unsplash will be compatible with NC21 in the future?

**Comment by RkuBr** [comment]
Any news about an update of Splash for NC 21 ? I miss my random / beautiful screen ! :)

**Comment by newhinton** [comment]
I'll take care of this today!

**Comment by newhinton** [comment]
https://apps.nextcloud.com/apps/unsplash
The update should be there soon!

**Comment by RkuBr** [comment]
Thank you so much ! You make my day ;)
