### ISSUE TITLE
After using this theme, my login interface will become very slow，Is it due to the network loading pictures?

### ISSUE THREAD

**Issue by rong280** [nextcloud/unsplash#87]
If the image is loaded from the network, will it be cached?

In addition, can I set to display only the pictures in the local folder?

**Comment by newhinton** [comment]
1) your browser should cache the image for a brief time, but generally it is fetched regularly.

2) Local folders are not supported currently

Can you check your network request tab in your browser and look for the requests that take the most time?

**Comment by rong280** [comment]
> 1. 您的浏览器应该在短时间内缓存该图像，但是通常会定期提取该图像。
> 2. 当前不支持本地文件夹
> 
> 您能否在浏览器中检查“网络请求”选项卡并查找花费时间最多的请求？

Ok，Thank you
