### ISSUE TITLE
Error message 'Failed' when changing settings

### ISSUE THREAD

**Issue by Darkknight33** [nextcloud/unsplash#88]
New installation of Nextcloud 21 via docker w/mariadb backend, added unsplash through apps. No other apps are installed.

Whenever I attempt to change any settings to unsplash via the check boxes, a red 'failed' message appears and the changes do not apply.

No error messages appear in the console.

Attached screen shots. 

![splash2](https://user-images.githubusercontent.com/571187/117868961-36c2a180-b268-11eb-8b59-7261cc16fec3.png)
![splash1](https://user-images.githubusercontent.com/571187/117868967-3aeebf00-b268-11eb-998c-c227c4301887.png)

**Comment by lineg-it** [comment]
Same issue on my side since Nextcloud 21.0 with postgres 14.
Updated to NC 22.2.1, but the issue still remains.

I've also deinstalled the app and reinstalled, but nothing works.
Found nothing in the nextcloud-logs, no network issue (firewall), nor any other logs listed an issue.

**Comment by newhinton** [comment]
Is this still a problem?

**Comment by CTONCD** [comment]
Hi please dont close this issue. I just install Nextcloud 24,0,1 with spash 1.2.5 and I have the same problem.
So if I could add a comment, le backgroung behind the top bar dont change the icon color and when the background is dark user couldn't see the icons (it is the same with white background and white icons) it could be better ;)

**Comment by CTONCD** [comment]
Exact, settings.js?v=10394b22-14:41 Refused to connect to 'http://xxxx.fr/apps/unsplash/settings/personal/set' because it violates the document's Content Security Policy.
how I can do ?

**Comment by newhinton** [comment]
@CTONCD Can you check the Content-Security-Policy in the network tab of your browser?

You can open the developer-tools with F12 (Both chrome and firefox work)

There you can open the network-tab, and then change a checkbox.
`http://xxxx.fr/apps/unsplash/settings/personal/set` this url will show up as a POST request. If you click on this you can see the header of the answer, and there should be a line which looks roughly like this:

`
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'`

What does it say in your browser?

Oh by the way: you should really _**not**_ run your cloud with http. Thats a big security-issue, and if you need a certificate check out [Let's Encrypt](https://letsencrypt.org/)

**Comment by newhinton** [comment]
Any news? Otherwise i will close this. This specific setting will be removed for nextcloud 25 anyway, so this wil be overcome by events.

**Comment by newhinton** [comment]
No further information was provided.
