### ISSUE TITLE
Update Nextcloud version 22 

### ISSUE THREAD

**Issue by adripo** [nextcloud/unsplash#89]
Please update for nextcloud version 22.

**Comment by newhinton** [comment]
The app still works as expected, you can enable it with "enable untested app" if you have not done so already.
I will change the version and upload a new release tomorrow morning

**Comment by newhinton** [comment]
https://github.com/nextcloud/unsplash/releases/tag/1.2.3

**Comment by adripo** [comment]
Thank you!
