### ISSUE TITLE
URL to photo

### ISSUE THREAD

**Issue by starlyth** [nextcloud/unsplash#9]
I would love to know the url of the photo; display it in small print on the bottom, for example. It should probably be an option, as I'm sure there are many who wouldn't want that to show up on the fantastic login screen.

**Comment by ToeJet** [comment]
Ditto.    Came across a few neat ones that would be fun to know more one.

**Comment by jancborchardt** [comment]
Yep, that would be nice. Contributions for this are very welcome. :)

**Comment by tau-ri** [comment]
Hi folks,
the url is coded in the app...
https://source.unsplash.com/random/featured/?nature

**Comment by jancborchardt** [comment]
@tau-ri yes – but people are asking about the actual URL of the photo which is randomly put out, which is a different one every time. :)

**Comment by ticevi** [comment]
I'm working on it and found a solution with dynamic css (execute php inside a css file).
The problem ist, that Nextcloud does not support these kind of files.
Has somebody a solution how to implement this file

**Comment by ticevi** [comment]
As a saw in #17 there is work all ready done to provide css trough php. Now I'm getting the actual url from the header redirect. When an other url is set there could be no information

**Comment by newhinton** [comment]
maybe you could also gather exif-metadata from the image, and display the location or content of the image, windows10-loginscreen-stlye

**Comment by marius-wieschollek** [comment]
I did not check, but i assume that unsplash removes all exif data when converting the images.
But the full api give a lot of extra information. You can get author information, description, image color and the location of the image from the api. For some reason you can't get the title.
I [added](https://github.com/jancborchardt/unsplash/pull/29) some information in the login page and in the notification menu and if you click on it a new tab is opened with the related unsplash page.
![grafik](https://user-images.githubusercontent.com/8255857/45257188-64156e00-b3a2-11e8-8e10-d9042b11010d.png)
