### ISSUE TITLE
Feature Request - Support for Screens > 1080p

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/unsplash#90]
It would be nize if the app has full scalable pictures, that depending on which screensize the client has, the screen will be filled beautifully. Especially at 4k Screens.
Alternative it would be nice if the admin can select the resolution of the pictures in the settings.

**Comment by MrLoverLoverMMMM** [comment]
OK, thanks for the statusupdate. I would be happy about such a feature. Moreover the pictures should be in the new picture formats like WebP and AVIF for even faster loading.

**Comment by MrLoverLoverMMMM** [comment]
+ If possible an option that the picture is chust variable at the login sceen not in the whole cloud and header. Otherwise every change in an app triggers a new picture.

**Comment by crasherwosa** [comment]
I have also installed the Splash app. However, I also find it a pity that the images are loaded unsharp. 

Especially in this day and age with larger screen resolutions, the images should be loaded in a larger format.

Optinal it would also be an added value that it can each set the format size via a Einstellugnsmöglichkeit, in the app.

Is there anything planned in the meantime? Or can I manually already set something like that? If so, how?

**Comment by newhinton** [comment]
@crasherwosa You can always edit the unsplash url manually. You need to edit https://github.com/nextcloud/unsplash/blob/134ccfeafe6b192529482449cc0cf05aa60f3feb/css/login.css#L4

this file for the login, there you can choose what to display. If you find the appropriate url for the unsplash-api you can control it by yourself

**Comment by crasherwosa** [comment]
Thank you for your feedback. I do not host my Nextcloud myself and do not have access via FTP/FTPS to the files. I therefore only have access to the web view. Can I therefore also make the settings/link change? And how?

**Comment by MrLoverLoverMMMM** [comment]
If you use that url in the app:
https://source.unsplash.com/featured/3840x2160?nature,nature
It will be fixed ;)
I suggest to implement a drop down or text input field and make the resolution a variable.
like: https://source.unsplash.com/featured/WIDTHxHEIGHT?nature,nature

**Comment by crasherwosa** [comment]
> If you use that url in the app:

But where can I store this link in the app? I have but no possibilities to change the link in the app? The only thing I can do under Settings/Splash is this?:

<img width="1003" alt="Bildschirmfoto 2022-03-09 um 12 22 03" src="https://user-images.githubusercontent.com/100469986/157432207-534c3ffd-23a3-40bf-8f0c-f6bf9b27977c.png">

- Use a random image as background of the navigation bar 
- Use a random image as background of the dashboard

**Comment by MrLoverLoverMMMM** [comment]
This is currently not possible.
But I hope someone will implement it :)

**Comment by crasherwosa** [comment]
Ahh okay, I thought that was already possible now and I didn't see it. 

That would be very very good indeed. Let's hope for the best :).

**Comment by newhinton** [comment]
@MrLoverLoverMMMM @crasherwosa There is already a pullrequest that implements more provider, but it needs a technical review. If you are up for it, you could take a look!

**Comment by MarcoLeongDev** [comment]
For those who are finding the css files, they are `login.css` and `dashboard.css` at directory `/var/www/html/custom_apps/unsplash/css`

**Comment by crasherwosa** [comment]
> @MrLoverLoverMMMM @crasherwosa There is already a pullrequest that implements more provider, but it needs a technical review. If you are up for it, you could take a look!

I would love to do it, but unfortunately have no experience at all how to do something like this. Was hoping for someone else :)

> For those who are finding the css files, they are `login.css` and `dashboard.css` at directory `/var/www/html/custom_apps/unsplash/css`

I don't have FTP access to my Nextcloud.

**Comment by newhinton** [comment]
I have updated the dev-branch. It contains my current iteration of more customizability and more image-provider. Testing is higly appreciated!

**Comment by newhinton** [comment]
Moved. See https://github.com/nextcloud/unsplash/discussions/94
