### ISSUE TITLE
Feature Request for Checkbox to show splash picture only at login screen

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/unsplash#91]
If possible an option that the picture is just used at the login sceen not in the whole cloud, especially not in the header. 
Otherwise every change in an app triggers a new picture + Elements in the header (menu of nextcloud) are depending on the picture not readable anymore.

Alternative the pictures from the splash collection could be reloaded only at the login screen and not on each click in the nextcloud menu.

**Comment by marius-wieschollek** [comment]
You can configure this in the settings. In the Admin settings in the "Design" section or in the user settings of your account in the "Splash" settings.

**Comment by MrLoverLoverMMMM** [comment]
perfect, thanks :)
