### ISSUE TITLE
TOTP does not follow login style

### ISSUE THREAD

**Issue by newhinton** [nextcloud/unsplash#97]

**Comment by skjnldsv** [comment]
Fixed with 25
![image](https://user-images.githubusercontent.com/14975046/170741985-41593720-f653-4080-bbbd-bcc1639474cc.png)

**Comment by newhinton** [comment]
Is this fixed for all currently supported versions? 

did that also fix the custom css loading, or just the background image loading?

**Comment by skjnldsv** [comment]
Login design is also applied, that include dark/light theme and primary colours

**Comment by newhinton** [comment]
@skjnldsv It is still impossible to load css on the `core.TwoFactorChallenge.showChallenge`-route. It tries to redirect the added header from a public page.

**Comment by skjnldsv** [comment]
@newhinton Adding css?
Why are you adding css? The totp style is compliant to wgat the login is using now. That's what this issue is about

![image](https://user-images.githubusercontent.com/14975046/193547746-1f005e82-253c-466d-bb37-2621a1a891e8.png)

**Comment by newhinton** [comment]
But this is about unsplash. We change the login screen, and then it does not match anymore.

**Comment by skjnldsv** [comment]
See linked PR
